### ISSUE TITLE
Tool used to generate lib\src\constants\constants.dart should be included.

### ISSUE THREAD

**Issue by timmaffett** [whiplashoo/flutter_font_picker#11]
I am assuming that there is a dart program (tool) that is used to generate the `constants.dart` file.
It would make sense to include this in a `tool\` or `generator\` subdirectory so that users have the option of regenerating this file themselves when the GoogleFonts package is updated to include new fonts (as it recently was updated to 4.0.3).

The tool should also be updated to write a header to the `constants.dart` file to specify the version of the GoogleFonts package it was generated for and the command used to generate it (ie. something like "Excecute `dart run tools\updateConstants.dart` from the root of the package to regenerate this file"). 

I would assume you are generating this file from information returned by the google fonts rest api as described [here](https://developers.google.com/fonts/docs/developer_api).  
This tool would require the user to create their own key as described [here](https://support.google.com/googleapi/answer/6158862?hl=en&ref_topic=7013279).
The page at [https://developers.google.com/fonts/docs/developer_api](https://developers.google.com/fonts/docs/developer_api) does include an 'execute' button which automatically grabs the latest json file.  Optionally we could allow the tool to read this json from a local file so that generating an API key was not required.

If you have not already created such a tool I would be happy to create one, otherwise I would be more than happy to clean up any existing code that exists to generate the `constants.dart` file and submit a PR (if you could provide the existing source).

What I am imagining doing is taking the font list from the google_fonts version specified in the pubspec.yaml file and then looking up each included font in the json file from the google fonts api and retrieving the required data.. and then writing out the new constants.dart file.

**Comment by timmaffett** [comment]
I went ahead and created PR #12 which implements what I am describing here.

**Comment by whiplashoo** [comment]
Closed via #12.
