### ISSUE TITLE
Upgrade dependencies to the latest version

### ISSUE THREAD

**Issue by simonpham** [whiplashoo/flutter_font_picker#3]

**Comment by whiplashoo** [comment]
[Version 1.4.0](https://github.com/whiplashoo/flutter_font_picker/commit/ef022b9938cf1363560b9adc0f5f96d05f7f3000) is now updated and compatible with Flutter 3 and google_fonts: ^3.0.1.

**Comment by whiplashoo** [comment]
@simonpham It was indeed! 🙌 

Mind if I ask how you are using this package in your project? I haven't found any use of it in the wild, so it would be interesting to know!

**Comment by simonpham** [comment]
> @simonpham It was indeed! 🙌
> 
> Mind if I ask how you are using this package in your project? I haven't found any use of it in the wild, so it would be interesting to know!

We are using it for a feature of [FluxBuilder](https://fluxbuilder.com) - a drag-and-drop tool for building mobile apps. You can try it out :D

**Comment by whiplashoo** [comment]
OK, that looks so cool! Good job! 🎊
