### ISSUE TITLE
"googleFonts"-Parameter does not seem to have any effect

### ISSUE THREAD

**Issue by amsgo** [whiplashoo/flutter_font_picker#6]
When building the example-project on Flutter 3.3.8 I always see the full list of ALL google fonts, no matter what fonts I include in this list. It seems this is not the intended behaviour?

**Comment by whiplashoo** [comment]
Indeed, thanks for reporting this. It is now fixed in v1.1.0.

**Comment by amsgo** [comment]
Looks good, thank you very much!
