### ISSUE TITLE
Updating the GoogleFonts package to the current version results in null references within picker_font.dart

### ISSUE THREAD

**Issue by timmaffett** [whiplashoo/flutter_font_picker#9]
First of all, thank you for your great package!

When updating the GoogleFonts package to 4.0.3 (the current version), and then using newly included fonts, I discovered that this results in null references within the `picker_font.dart` file when indexing into `googleFontsDetails[]` with the new font names.

This is due to the fact that the `constants.dart` file was generated with a previous list of available google fonts which is now outdated.

This can be remedied by updating `constants.dart`, but additionally `picker_font.dart` should be also be protected from these null dereferences.

**Comment by whiplashoo** [comment]
Updated! Thanks again.
